import time
from pathlib import Path
from fastapi import APIRouter, UploadFile, File, HTTPException
from fastapi.responses import JSONResponse

from app.core.model_loader import registry
from app.schemas.prediction import PredictionResponse, ImageSet
from app.utils.image import (
    validate_upload,
    load_image,
    preprocess_for_cnn,
    encode_image,
    bgr_to_rgb_encoded,
)
from app.services.inference import run_cnn
from app.services.gradcam import generate_heatmap, overlay_heatmap
from app.services.segmentation import run_segmentation

router = APIRouter()

CLINICAL_NOTE = (
    "This result is generated by a research model and is not a clinical diagnosis. "
    "Always consult a qualified ophthalmologist for medical advice."
)


@router.post("/predict", response_model=PredictionResponse)
async def predict(file: UploadFile = File(...)):

    # ── Guard: models must be loaded ─────────────────────────────
    if not registry.is_ready:
        raise HTTPException(
            status_code=503,
            detail="Models are still loading. Please retry in 30 seconds.",
        )

    start = time.perf_counter()

    # ── Read and validate the uploaded file ──────────────────────
    file_bytes = await file.read()
    validate_upload(file.filename or "upload", file_bytes)

    # ── Load image ───────────────────────────────────────────────
    img_bgr = load_image(file_bytes)

    # ── CNN inference ────────────────────────────────────────────
    cnn_input  = preprocess_for_cnn(img_bgr)
    cnn_result = run_cnn(registry.cnn, cnn_input)

    # ── Grad-CAM ─────────────────────────────────────────────────
    heatmap    = generate_heatmap(registry.cnn, cnn_input)
    overlay    = overlay_heatmap(img_bgr, heatmap)

    # ── Segmentation + CDR ───────────────────────────────────────
    seg_result = run_segmentation(registry.disc, registry.cup, img_bgr)

    # ── Encode all images to base64 ──────────────────────────────
    import cv2
    original_resized = cv2.resize(img_bgr, (224, 224))

    images = ImageSet(
        original             = bgr_to_rgb_encoded(original_resized),
        heatmap_overlay      = bgr_to_rgb_encoded(overlay),
        disc_mask            = encode_image(seg_result["disc_mask"]),
        cup_mask             = encode_image(seg_result["cup_mask"]),
        segmentation_overlay = bgr_to_rgb_encoded(seg_result["overlay_bgr"]),
    )

    elapsed_ms = int((time.perf_counter() - start) * 1000)

    return PredictionResponse(
        prediction       = cnn_result.prediction,
        probability      = cnn_result.probability,
        confidence       = cnn_result.confidence,
        cdr              = seg_result["cdr"],
        cdr_risk         = seg_result["cdr_risk"],
        processing_time_ms = elapsed_ms,
        images           = images,
        clinical_note    = CLINICAL_NOTE,
    )